baseURL: "https://yasharma.com/"
title: Yash Sharma
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Yash Sharma"
  description: "Personal website and blog of Yash Sharma"
  keywords: [Blog, Portfolio, Travel, Cities, Immigration]
  author: "Yash Sharma"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  mainSections: []  # Empty array means no sections show on homepage


  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

  label:
    text: "Yash Sharma"
    icon: /favicon-32x32.png
    iconHeight: 35

  # Remove or comment out homeInfoParams since _index.md will handle homepage content
  # homeInfoParams:
  #   Title: "Hi there, I am Yash!"
  #   Content: Welcome to my blog.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/yasharmaa"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 20
    - identifier: now
      name: now
      url: /now/
      weight: 30

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    codeFences: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON